### ISSUE TITLE
could not convert string to float: ''

### ISSUE THREAD

**Issue by Shilu545** [kentnf/iTAK#10]
Hi,
Thank you very much for developing this software. When running it, I encountered the following error. I can run the test_seq file successfully, but I have changed different nucleotide and protein sequences, the error always like this:

HMMER is installed.
Database file ~/biosoft/iTAK/iTAK-2.0.2/database/Tfam_domain.hmm is ready.
Database file ~/biosoft/iTAK/iTAK-2.0.2/database/TF_selfbuild.hmm is ready.
Database file ~/biosoft/iTAK/iTAK-2.0.2/database/PlantsPHMM3_89.hmm is ready.
Database file ~/biosoft/iTAK/iTAK-2.0.2/database/Plant_Pkinase_fam.hmm is ready.
Database file ~/biosoft/iTAK/iTAK-2.0.2/database/Pkinase_sub_WNK1.hmm is ready.
Database file ~/biosoft/iTAK/iTAK-2.0.2/database/Pkinase_sub_MAK.hmm is ready.
Namespace(classify=False, frame='6', mode='quick', output='./qiai.pro.itak', process=4, seq_files=['qiai.pro.fasta'], specific=None, update=False)
Traceback (most recent call last):
  File "~/biosoft/iTAK/iTAK-2.0.2/iTAK.py", line 1179, in <module>
    main()
  File "~/biosoft/iTAK/iTAK-2.0.2/iTAK.py", line 1176, in main
    itak_identify(args, bin_path, dbs_path, database_files)
  File "~/biosoft/iTAK/iTAK-2.0.2/iTAK.py", line 909, in itak_identify
    qid_tid = itak_tf_identify(hmmscan_hit_1, hmmscan_detail_1, hmmscan_hit_1b, ga_cutoff, tf_rule)
  File "~/biosoft/iTAK/iTAK-2.0.2/iTAK.py", line 679, in itak_tf_identify
    rule_id = compare_rule(hits, score, hits_s, score_s, tf_rule)
  File "~/biosoft/iTAK/iTAK-2.0.2/iTAK.py", line 555, in compare_rule
    score = list(map(float, hmm_score.split('\t')))
ValueError: could not convert string to float: ''

I am looking forward to hearing from you.

**Comment by gacds3** [comment]
Could you solve it? I got the same problem and the only thing I could do for now was to subsample and submit my data to itak online

**Comment by ShuaiBinyu** [comment]
I also got this question, do you have any other solutions?

**Comment by gacds3** [comment]
> I also got this question, do you have any other solutions?

I downloaded a previous version, v 1.8, which is still in Perl, and ir worked

**Comment by ShuaiBinyu** [comment]
<img width="698" height="262" alt="Image" src="https://github.com/user-attachments/assets/9b3876ee-1535-4ad4-b18c-61a3d09b33c4" />

<img width="809" height="347" alt="Image" src="https://github.com/user-attachments/assets/be58de9d-aa4d-4ea0-a927-8309d61a8971" />

I checked the intermediate file and found that the "score" here might be empty. So I made a modification.

<img width="879" height="165" alt="Image" src="https://github.com/user-attachments/assets/7c512377-5731-451f-893d-e09c2b0c1a6d" />
